import TopNavigation from '../components/homePageAllComponents/TopNavigation'
import Head from 'next/head'
import Navbar from '../components/homePageAllComponents/Navbar';
import Banner from '../components/homePageAllComponents/banner/Banner';
import MotivateSection from '../components/homePageAllComponents/MotivateSection/MotivateSection';
import WellComeSection from '@/components/homePageAllComponents/wellComeSection/WellComeSection';
import DonateRegistration from '@/components/homePageAllComponents/donateRegistration/DonateRegistration';


export default function Home() {
  return (
    <>
      <Head>
        <title>Blood Donate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <TopNavigation/>
          <Navbar/>
          <Banner/>
          <MotivateSection/>
          {/* <OurServicesSticky/> */}
          <WellComeSection/>
          <DonateRegistration/>
      
      </main>
    </>
  )
}
